"""Tool→subdir routing table and related constants for NOCAP."""

from __future__ import annotations

SUBDIRS = frozenset({"recon", "loot", "exploitation", "screenshots", "notes"})

# Flags whose *next* token is a value to be consumed (not added to filename)
SKIP_FLAGS = frozenset({
    "-w", "--wordlist",
    "-u", "--url",
    "-o", "--output",
    "-oN", "-oX", "-oA", "-oG", "-oS", "-oJ",
    "-T", "--timeout",
    "--threads", "-t",
    "--rate",
    "-H", "--header",
    "-d", "--domain",
    "-f", "--file", "--hash-file",
    "-mc", "-fc",
    "-p",
})

# Auto tool→subdir routing (opt-in via --auto / -a)
TOOL_SUBDIRS: dict[str, str] = {
    # ── recon: network scanning & port discovery ─────────────────────────────
    "nmap": "recon",
    "nmap-parse-output": "recon",
    "rustscan": "recon",
    "masscan": "recon",
    "autorecon": "recon",
    "udpx": "recon",
    "divideandscan": "recon",
    "naabu": "recon",
    "netdiscover": "recon",
    "fping": "recon",
    "arp-scan": "recon",
    "zmap": "recon",
    "unicornscan": "recon",
    # recon: web fuzzing & directory brute-force
    "gobuster": "recon",
    "feroxbuster": "recon",
    "ffuf": "recon",
    "wfuzz": "recon",
    "dirsearch": "recon",
    "dirb": "recon",
    "arjun": "recon",
    "kr": "recon",            # kiterunner
    "wuzz": "recon",
    # recon: web fingerprinting & active scanning
    "whatweb": "recon",
    "nikto": "recon",
    "nuclei": "recon",
    "httpx": "recon",
    "httprobe": "recon",
    "http": "recon",            # httpie
    "curl": "recon",
    "wget": "recon",
    "hakrawler": "recon",
    "katana": "recon",
    "gau": "recon",
    "bbot": "recon",
    "uncover": "recon",
    "chaos": "recon",
    "alterx": "recon",
    "hakrevdns": "recon",
    "jsluice": "recon",
    "linkfinder": "recon",
    "robotstester": "recon",
    "patator": "recon",
    "ssh-audit": "recon",
    "gospider": "recon",
    "cariddi": "recon",
    "searchsploit": "recon",
    "trufflehog": "recon",
    "gitleaks": "recon",
    "git-dumper": "recon",
    # recon: CMS scanners
    "wpscan": "recon",
    "wpprobe": "recon",
    "joomscan": "recon",
    "droopescan": "recon",
    "drupwn": "recon",
    "cmsmap": "recon",
    "moodlescan": "recon",
    # recon: SSL/TLS & web infra
    "testssl": "recon",
    "sslscan": "recon",
    "wafw00f": "recon",
    "cors_scan": "recon",
    # recon: DNS & subdomain enumeration
    "dnsx": "recon",
    "massdns": "recon",
    "shuffledns": "recon",
    "fierce": "recon",
    "amass": "recon",
    "subfinder": "recon",
    "sublist3r": "recon",
    "findomain": "recon",
    "assetfinder": "recon",
    "dnsenum": "recon",
    "dnsrecon": "recon",
    "dnschef": "recon",
    "waybackurls": "recon",
    "dig": "recon",
    "whois": "recon",
    # recon: SMB / RPC / LDAP enumeration
    "enum4linux": "recon",
    "enum4linux-ng": "recon",
    "ldapsearch": "recon",
    "smbclient": "recon",
    "smbmap": "recon",
    "smbclientng": "recon",
    "rpcclient": "recon",
    "windapsearch": "recon",
    "ldeep": "recon",
    "pywerview": "recon",
    "godap": "recon",
    "manspider": "recon",
    "msprobe": "recon",
    "adidnsdump": "recon",
    "daclsearch": "recon",
    "nbtscan": "recon",
    "smtp-user-enum": "recon",
    "scrtdnsdump": "recon",
    "pysnaffler": "recon",
    # recon: SNMP & NFS
    "snmpwalk": "recon",
    "snmpenum": "recon",
    "onesixtyone": "recon",
    "showmount": "recon",
    # recon: Kerberos, AD & BloodHound collection
    "kerbrute": "recon",
    "netexec": "recon",
    "crackmapexec": "recon",
    "sprayhound": "recon",
    "smartbrute": "recon",
    "ldapdomaindump": "recon",
    "bloodhound-python": "recon",
    "rusthound": "recon",
    "rusthound-ce": "recon",
    # recon: OSINT
    "theHarvester": "recon",
    "recon-ng": "recon",
    "spiderfoot": "recon",
    "finalrecon": "recon",
    "maltego": "recon",
    "sherlock": "recon",
    "maigret": "recon",
    "holehe": "recon",
    "ghunt": "recon",
    "phoneinfoga": "recon",
    "censys": "recon",
    "GitFive": "recon",
    "photon": "recon",
    # recon: cloud
    "scout": "recon",          # ScoutSuite
    "cloudsplaining": "recon",
    "prowler": "recon",
    "cloudmapper.py": "recon",
    # recon: WiFi passive discovery
    "bettercap": "recon",
    "hcxdumptool": "recon",
    "airodump-ng": "recon",
    "kismet": "recon",
    # ── screenshots ───────────────────────────────────────────────────────────
    "eyewitness": "screenshots",
    "EyeWitness": "screenshots",
    "gowitness": "screenshots",
    "aquatone": "screenshots",
    "webscreenshot": "screenshots",
    # ── loot: password cracking ───────────────────────────────────────────────
    "hashcat": "loot",
    "john": "loot",
    "hydra": "loot",
    "medusa": "loot",
    "legba": "loot",
    "fcrackzip": "loot",
    "pdfcrack": "loot",
    "nth": "loot",             # name-that-hash
    "haiti": "loot",
    "pkcrack": "loot",
    "ncrack": "loot",
    "aircrack-ng": "loot",
    "hcxpcapngtool": "loot",
    # loot: forensics & steganography
    "volatility": "loot",
    "volatility3": "loot",
    "binwalk": "loot",
    "foremost": "loot",
    "steghide": "loot",
    "stegseek": "loot",
    "exiftool": "loot",
    "zsteg": "loot",
    # loot: credential dumping & extraction
    "pypykatz": "loot",
    "lsassy": "loot",
    "DonPAPI": "loot",
    "donpapi": "loot",
    "gosecretsdump": "loot",
    "dploot": "loot",
    "masky": "loot",
    "crackhound": "loot",
    "keytabextract": "loot",
    "PCredz": "loot",
    "firefox_decrypt": "loot",
    # ── exploitation: frameworks & C2 ────────────────────────────────────────
    "msfconsole": "exploitation",
    "msfvenom": "exploitation",
    "msfdb": "exploitation",
    "routersploit": "exploitation",
    "sliver-server": "exploitation",
    "sliver-client": "exploitation",
    "ps-empire": "exploitation",
    "havoc": "exploitation",
    "Villain.py": "exploitation",
    "pwncat-vl": "exploitation",
    "pwncat-cs": "exploitation",
    # exploitation: tunneling & pivoting
    "ligolo-ng": "exploitation",
    "chisel": "exploitation",
    "socat": "exploitation",
    # exploitation: web
    "sqlmap": "exploitation",
    "weevely": "exploitation",
    "xsstrike": "exploitation",
    "nosqlmap": "exploitation",
    "gopherus": "exploitation",
    "ssrfmap": "exploitation",
    "bolt": "exploitation",
    "kadimus": "exploitation",
    "fuxploider": "exploitation",
    "ysoserial": "exploitation",
    "phpggc": "exploitation",
    "jdwp-shellifier": "exploitation",
    "byp4xx": "exploitation",
    "h2csmuggler": "exploitation",
    "smuggler": "exploitation",
    "tomcatWarDeployer": "exploitation",
    "clusterd": "exploitation",
    "token-exploiter": "exploitation",
    "XXEinjector": "exploitation",
    "php_filter_chain_generator": "exploitation",
    "dalfox": "exploitation",
    "commix": "exploitation",
    "tplmap": "exploitation",
    "ghauri": "exploitation",
    "jwt_tool": "exploitation",
    "swaks": "exploitation",
    # exploitation: AD / Windows
    "evil-winrm": "exploitation",
    "evil-winrm-py": "exploitation",
    "mitm6": "exploitation",
    "ntlmrelayx.py": "exploitation",
    "krbrelayx.py": "exploitation",
    "aclpwn": "exploitation",
    "coercer": "exploitation",
    "petitpotam.py": "exploitation",
    "dfscoerce.py": "exploitation",
    "shadowcoerce.py": "exploitation",
    "pywhisker": "exploitation",
    "targetedKerberoast.py": "exploitation",
    "bloodyAD": "exploitation",
    "autobloody": "exploitation",
    "gpoddity": "exploitation",
    "goexec": "exploitation",
    "remotemonologue.py": "exploitation",
    "sccmhunter.py": "exploitation",
    "pxethief": "exploitation",
    "pre2k": "exploitation",
    "passthecert.py": "exploitation",
    "certipy": "exploitation",
    "noPac.py": "exploitation",
    "privexchange.py": "exploitation",
    "ms14-068.py": "exploitation",
    "zerologon-exploit": "exploitation",
    "abuseACL": "exploitation",
    "sccmsecrets.py": "exploitation",
    "pywsus.py": "exploitation",
    "pygpoabuse.py": "exploitation",
    # exploitation: impacket lateral movement
    "psexec.py": "exploitation",
    "wmiexec.py": "exploitation",
    "smbexec.py": "exploitation",
    "atexec.py": "exploitation",
    "dcomexec.py": "exploitation",
    "secretsdump.py": "exploitation",
    "GetNPUsers.py": "exploitation",
    "GetUserSPNs.py": "exploitation",
}
